export const UPDATE_NEXT_FILTER = 'FILTER::UPDATE_NEXT_FILTER'
export const APPLY_FILTERS = 'FILTER::APPLY_FILTERS'
export const CANCEL_FILTERS = 'FILTER::CANCEL_FILTERS'
export const RESET_FILTERS = 'FILTER::RESET_FILTERS'