version: "3"
services:
  keycloak:
    image: jboss/keycloak:6.0.1
    ports:
    - "8901:8080"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_IMPORT: "/tmp/kaas-dev.json"
    volumes:
    - ${PWD}/kaas-dev.json:/tmp/kaas-dev.json